name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements file if you have one

    - name: Build Executable
      working-directory: ./src
      run: pyinstaller.exe --onefile --name VISREX --icon=src\gui\assets\app_icon.ico --noconsole --hidden-import=psutil --hidden-import=pkgutil --hidden-import=PyQt6.sip --hidden-import=PyQt6.QtCore --hidden-import=PyQt6.QtWidgets --hidden-import=qtawesome --hidden-import=qdarktheme --hidden-import=graphviz --hidden-import=pygetwindow --hidden-import=pyautogui --hidden-import=pymem --hidden-import=markdown --hidden-import=RPA --hidden-import=RPA.Windows --add-data "gui\assets\*:gui\assets\" --add-data "resources_rc.py;." .\main.py

    - name: Archive Executable
      uses: actions/upload-artifact@v2
      with:
        name: VISREX
        path: dist

  # release:
  #   runs-on: windows-latest
  #   needs: build
  #   steps:
  #   - name: Download Executable
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: VISREX
  #       path: .

  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: Release ${{ github.ref }}
  #       body: |
  #         Changes in this release:
  #         - Add your release notes here

  #   - name: Upload Executable to Release
  #     id: upload-release-asset
  #     uses: actions/upload-release-asset@v1
  #     with:
  #       upload_url: ${{ steps.create_release.outputs.upload_url }}
  #       asset_path: ./your_script.exe  # Adjust the file extension if necessary
  #       asset_name: your_script.exe
  #       asset_content_type: application/octet-stream
